### PR TITLE
Intakifying and cleaning Carbon Flux

### PR DESCRIPTION
**Pull request by jsignell**
~@jlstevens @stsievert  This splits Carbon Flux into 2 separate notebooks: *Visualization* and *Prediction*. Visualization is done and should be built for the website. Prediction is the one that Scott is still working on and his PRs should be rebased once this lands.~

This does a substantial clean of Carbon Flux adds a lot of viz including dashboards, and moves the umap stuff to a separate notebook in the `carbon_flux_umap` branch.

### CODE REVIEW

**Comment by jbednar** [comment]
Prediciton?

**Comment by jsignell** [comment]
https://anaconda.org/jsignell/carbon_flux_visualization/notebook
https://anaconda.org/jsignell/carbon_flux_prediction/notebook

**Comment by jsignell** [comment]
Just note to self to send a reminder to Grey when this goes in.

**Comment by jsignell** [comment]
I am going to merge this when it goes green.

**Comment by jsignell** [comment]
Note that I pushed an evaluated version to the `evaluated` branch as well. I will now tag a dev release of the website.

**Pull request merged**
