### PR TITLE
Added the Carbon_Flux notebook

### PR DESCRIPTION
**Pull request by jlstevens**
This notebook is work in progress that is based on the work in [nee_data_fusion](https://github.com/greyNearing/nee_data_fusion). As such, this notebook relies on the files available in that repository which can be made accessible using a suitable symbolic link in the `examples` directory. The RSIF `.mat` file is also required.

Currently the goal of this notebook is as follows:

1. Capture an understanding of the science and goals behind the carbon monitoring project.
2. Show how the data munging required can be achieved easily in Python.
3. Demonstrate how this data can be easily visualized.
4. Demonstrate the ML component of the task.

Currently the first three tasks are partially completed with ongoing work on the 4th step.

### CODE REVIEW

**Comment by stsievert** [comment]
Thanks for this @jlstevens. In the meeting yesterday, a variable indicating what climate was present at every fluxnet station. When will we see these variables?

I am mostly working on task 2 right now, given the updates yesterday.

**Comment by jlstevens** [comment]
@stsievert That variable describing the climate/ecology classifications is very important but to my knowledge this is not yet in the CSV files of the `nee_data_fusion` repo. Either those CSV files will be updated or we will need a new file mapping the fluxnet sites to their classifications.

I'll also mention that for now we will make use of the [pyviz environment](http://pyviz.org/installation.html) to supply our dependencies. As the various ML libraries come into play, we will need to find a way of specifying those too.

**Comment by mmccarty** [comment]
@stsievert @jlstevens @jbednar Can we merge this PR?

**Comment by stsievert** [comment]
Works for me. My changes were only to code cells, which don't look changed (and tools like [nbdime] will be useful in resolving any merge conflicts).

[nbdime]:https://nbdime.readthedocs.io/en/stable/

**Pull request merged**
