### PR TITLE
Landsat multi-band spectral clustering

### PR DESCRIPTION
**Pull request by mmccarty**

### CODE REVIEW

**Comment by mmccarty** [comment]
@jbednar, I think I've got this working now for multiple bands.  I've committed with a smaller sample to help with debugging the labels plot at the end.

@jlstevens Can you take a look at the labels plot at the end of the notebook.  The artifacts we saw earlier seem to be a plotting issue. Note, the matplotlib version looks good. 

screen shot 2018-09-07 at 2 27 14 pm

**Comment by mmccarty** [comment]
@jlstevens I think I've figured it out.  I was a problem with `regrid` which I don't think we need.  PR updated.

**Comment by jlstevens** [comment]
@mmccarty As you noticed, to don't have to use `regrid` but you *should* be able to. @jbednar Any idea why regrid might cause such artifacts? Seems very likely that something is funny with the datashader output...

**Comment by jbednar** [comment]
Right; regrid should be safe in general; it should just resample, and with a uniform pattern like on the lake area it should have very little effect.  It would be nice to pull out a more specific test case that we can investigate.

**Comment by mmccarty** [comment]
@jbednar @jlstevens I'll trying to come up with a minimal example that reproduces the problem.

**Pull request merged**
